name: Translation Sync

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  sync:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    container:
      image: owncloudci/transifex:latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: core
            mode: make
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: activity
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: announcementcenter
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: brute_force_protection
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: calendar
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: contacts
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: customgroups
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: diagnostics
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: drawio
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: external
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: files_antivirus
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: files_external_dropbox
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: files_external_ftp
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: files_paperhive
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: files_primary_s3
            mode: make
            branch: master
            sub_path: .
            package_manager: npm

          - name: files_mediaviewer
            mode: make
            branch: master
            sub_path: .
            package_manager: npm

          - name: files_texteditor
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: files_pdfviewer
            mode: make
            branch: master
            sub_path: .
            package_manager: npm

          - name: firstrunwizard
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: guests
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: impersonate
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: notes
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: notifications
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: oauth2
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: password_policy
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: richdocuments
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: twofactor_backup_codes
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: twofactor_totp
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: user_ldap
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: encryption
            mode: old
            branch: master
            sub_path: l10n
            package_manager: npm

          - name: ocis
            mode: make
            branch: master
            sub_path: .
            package_manager: npm

          - name: openidconnect
            mode: make
            branch: master
            sub_path: .
            package_manager: npm

          - name: web
            mode: make
            branch: master
            sub_path: .
            package_manager: pnpm

          - name: web-extensions
            mode: make
            branch: main
            sub_path: .
            package_manager: pnpm

          - name: android
            mode: native
            branch: master
            sub_path: .
            package_manager: npm

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: owncloud/${{ matrix.name }}
          ref: ${{ matrix.branch }}
          path: ${{ matrix.name }}
          fetch-depth: 0
          persist-credentials: false

      - name: Create translation directory
        if: matrix.mode == 'old'
        run: mkdir -p '${{ matrix.name }}/${{ matrix.sub_path }}'

      - name: Translation reader (make)
        if: matrix.mode == 'make'
        env:
          NO_INSTALL: "true"
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          if [ '${{ matrix.package_manager }}' = 'pnpm' ]; then
            npm install --silent --global --force "$(jq -r '.packageManager' < package.json)"
            pnpm config set store-dir ./.pnpm-store
            pnpm install
          fi
          make l10n-read

      - name: Translation reader (old)
        if: matrix.mode == 'old'
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          l10n '${{ matrix.name }}' read

      - name: Translation push (make)
        if: matrix.mode == 'make' && github.ref == 'refs/heads/master'
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          make l10n-push

      - name: Translation push (old)
        if: matrix.mode == 'old' && github.ref == 'refs/heads/master'
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          tx push -s --skip

      - name: Translation pull (make)
        if: matrix.mode == 'make'
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          make l10n-pull

      - name: Translation pull (old/native)
        if: matrix.mode != 'make'
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          tx pull -a --skip --minimum-perc=75 -f

      - name: Translation writer (make)
        if: matrix.mode == 'make'
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          make l10n-write

      - name: Translation writer (old)
        if: matrix.mode == 'old'
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          l10n '${{ matrix.name }}' write

      - name: Translation cleanup (make)
        if: matrix.mode == 'make'
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          make l10n-clean

      - name: Translation cleanup (old)
        if: matrix.mode == 'old'
        run: |
          cd '${{ matrix.name }}/${{ matrix.sub_path }}'
          find . -name "*.po" -type f -delete
          find . -name "*.pot" -type f -delete
          find . -name "or_IN.*" -type f -print0 | xargs -r -0 git rm -f
          find . -name "uz.*" -type f -print0 | xargs -r -0 git rm -f
          find . -name "yo.*" -type f -print0 | xargs -r -0 git rm -f
          find . -name "ne.*" -type f -print0 | xargs -r -0 git rm -f

      - name: Commit and push translations
        if: github.ref == 'refs/heads/master'
        uses: GuillaumeFalourd/git-commit-push@205c043bca2f932f7a48a28a8d619ba30eb84baf
        with:
          target_branch: ${{ matrix.branch }}
          commit_message: "[tx] updated from transifex"
          name: ownClouders
          email: devops@owncloud.com
          files: ${{ matrix.name }}
          empty: 0
          access_token: ${{ secrets.GIT_PUSH_PAT }}
